### ISSUE TITLE
May I ask what this used for?

### ISSUE THREAD

**Issue by crazy-canux** [artur-shaik/vimmer-dotfiles#1]
autocmd Filetype java,jsp no <F10> :wa<CR> :make compile<CR>

**Comment by artur-shaik** [comment]
Save file and run `make compile` command.

**Comment by crazy-canux** [comment]
sure.
May I ask how to use quickfix for java?

**Comment by artur-shaik** [comment]
Yeah, of cause. I usually use maven, so if I remember right everything done by `vim-scripts/Maven-Compiler` plugin.

**Comment by crazy-canux** [comment]
Ok, I see. Maven or ant? I'll pick one.
Thanks!
